server:
  port: 8080

spring:
  application:
    name: gateway-service
  redis:
    port: 6379
    host: localhost
  cloud:
    compatibility-verifier.enabled: false
    gateway:
      routes:
        - id: employeeservice
          uri: lb://EmployeeService
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - StripPrefix=0
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 100
                redis-rate-limiter.requestedTokens: 1
#           - KeyAuthFilter
        - id: bookservice
          uri: lb://BookService
          predicates:
            - Path=/api/v1/books/**
          filters:
            - StripPrefix=0
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 100
                redis-rate-limiter.requestedTokens: 1
            - AuthFilter
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

